name = "ChebyshevTransforms"
uuid = "2752694e-a3a0-42bd-9f17-5f3242da1ce6"
authors = ["Paul Nemec <paul.nemec@tum.de>"]
version = "0.0.1"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
